version: "3"
services: 
    django:
        build: ./project
        volumes: 
            - ./project/work:/work
        ports: 
            - "5000:5000"
        tty: true
        environment:
            TZ: "Asia/Tokyo"