version: "3"
services:
    web:
        build: ./project/app
        volumes:
            - ./project/app:/work
        ports:
            - "5000:5000"
        tty: true
        environment:
            TZ: "Asia/Tokyo"
        env_file: 
            - ./.env.dev
        depends_on:
            - db
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=hello_django
            - POSTGRES_PASSWORD=hello_django
            - POSTGRES_DB=hello_django_dev

volumes:
    postgres_data: